### ISSUE TITLE
bin/rake db:seed fails because channel no longer has record_id column 

### ISSUE THREAD

**Issue by sebroeder** [roschaefer/story.board#399]
Seeding the database with the `db:seed` rake task fails because #357 removed the `record_id` column on the `channels` table, but it is still used in the seed file: https://github.com/roschaefer/story.board/blob/e2b25ec6907282268a5bee45103a89f3ac5c949a/db/seeds.rb#L30-L48.

When I understand the highlighted lines correctly, the intend is to associate each **existing report** with the two "standard" channels `sensorstory` and `chatbot`. The same code is repeated in a migration file: https://github.com/roschaefer/story.board/blob/e2b25ec6907282268a5bee45103a89f3ac5c949a/db/migrate/20170402092445_create_default_channels.rb

Since the association between `channel` and `report` does no longer exist, can the code block in question be safely removed?

I would propose to add the two standard channels `sensorstory` and `chatbot` to the seed on its own, since they are typical seed data. 

It is a little hard to work with this seed file, because we have a lot of data that is typically considered seed data scattered across many data migrations, so the seed gives an incomplete picture of the data that actually needs to be created for the production system. Data migrations are considered problematic by many Rails developers: https://robots.thoughtbot.com/data-migrations-in-rails. I would like to go through all the data migrations to find out what else is missing in the seed file.

If there are other cases like the now obsolete "every report must be associated with those two channels", I’d propose an `after_create` callback on the model class instead.

The complete error message of the failings rake task is as follows:

```
bin/rake db:seed
Running via Spring preloader in process 2872
rake aborted!
ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR:  column channels.report does not exist
LINE 1: SELECT  "channels".* FROM "channels" WHERE "channels"."repor...
                                                   ^
: SELECT  "channels".* FROM "channels" WHERE "channels"."report" = 1 AND "channels"."name" = $1 LIMIT $2
/Users/sebroeder/Developer/public/roschaefer/story.board/db/seeds.rb:31:in `block in <top (required)>'
/Users/sebroeder/Developer/public/roschaefer/story.board/db/seeds.rb:30:in `<top (required)>'
-e:1:in `<main>'
PG::UndefinedColumn: ERROR:  column channels.report does not exist
LINE 1: SELECT  "channels".* FROM "channels" WHERE "channels"."repor...
                                                   ^
/Users/sebroeder/Developer/public/roschaefer/story.board/db/seeds.rb:31:in `block in <top (required)>'
/Users/sebroeder/Developer/public/roschaefer/story.board/db/seeds.rb:30:in `<top (required)>'
-e:1:in `<main>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)
```

**Comment by sebroeder** [comment]
The same code block for creating default topics and channels is repeated a third time in in a rake task in [lib/tasks/channel.rake](https://github.com/roschaefer/story.board/blob/e2b25ec6907282268a5bee45103a89f3ac5c949a/lib/tasks/channel.rake). This is really hard to maintain.

I am currently leaning towards the following strategy to clean this up:

1. Make `seed.rb` a "real" seed file, that is: only use it to **create** data required in production into an empty database. So no more `find_or_create` in the seed file.
2. Update (and possibly rename) the rake task so that it can be run at any time to ensure certain data like our default topics and channels are in a known good state, using `find_or_create` etc.
3. If there is any setup, for example associations to default channels that every model instance must have after creation, move this out of the seed and rake task (?) into the model as an `after_create` callback (or proc on the association method. Rails 5.1 has a new feature to set default values for associations so I have to find out what was the way to do this before Rails 5.1).
4. Discourage the team to use data migrations in migration files going forward, any data should go into the seed.rb and/or the rake task. If there is a special case that absolutely needs a data migration in a migration file, this should be communicated in a git commit message, source code comment or similar. Can we agree on this? 
5. Since it is dangerous to delete migration files that are already in a shared git repository, maybe add a comment to all migration files with data migrations explain the point made under 4.)?

**Comment by roschaefer** [comment]
Yes, @sebroeder you are picking up a discussion that we had a couple of weeks ago. I strongly argued **against** creating data in migrations. By all means. I know the implications. Nevertheless, a former team member was very determined on that.

Our situation right now is that we create data in the migrations and the code sometimes expects that data to be present. Also, our tests are expecting that data to be present. Indeed, [this data here](https://github.com/roschaefer/story.board/blob/master/db/static_seeds.rb) is re-created after each cucumber scenario is run.

I like the idea to have the `seeds.rb` validated by our build server. Can you add a step to our `travis.yml` to seed the database?

I don't like the idea that every developer has to run `db:seed` all the time. The seeds should be optional. Everything that is not optional should go into a database migration.

But yes, you're right. Creating data in migrations is considered bad practice and the consequences will haunt you.

**Comment by roschaefer** [comment]
Also, try to avoid `before(:create)` callbacks. This will affect our tests. If necessary, add a default value in the form, when a user wants to e.g. create a new text component.
